services:
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=redhat
      - MYSQL_DATABASE=student_db
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - 8080:8080
    
    depends_on:
      - db
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend
volumes:
  mysql_data:
