apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-040ede311ff0a7c74
    fsType: ext4
    volumeAttributes: 
      storage.kubernetes.io/csiProvisionerIdentity: static
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - {key: topology.kubernetes.io/zone, operator: In, values: ["ap-south-1a"]}
